"""empty message

Revision ID: 04a56d5a9a42
Revises: 0da29d9e50a1
Create Date: 2018-10-15 16:11:31.138273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a56d5a9a42'
down_revision = '0da29d9e50a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_name'), 'seasons', ['name'], unique=False)
    op.add_column('races', sa.Column('season_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'races', 'seasons', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'races', type_='foreignkey')
    op.drop_column('races', 'season_id')
    #op.drop_index(op.f('ix_seasons_name'), table_name='seasons')
    op.drop_table('seasons')
    # ### end Alembic commands ###
