"""empty message

Revision ID: 05104e75a3e3
Revises: f96298d3220e
Create Date: 2018-10-12 14:58:38.516428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05104e75a3e3'
down_revision = 'f96298d3220e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glicko_ratings', sa.Column('races', sa.Integer(), nullable=False))
    op.add_column('glicko_ratings', sa.Column('school_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'glicko_ratings', 'races', ['races'], ['id'])
    op.create_foreign_key(None, 'glicko_ratings', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'glicko_ratings', type_='foreignkey')
    op.drop_constraint(None, 'glicko_ratings', type_='foreignkey')
    op.drop_column('glicko_ratings', 'school_id')
    op.drop_column('glicko_ratings', 'races')
    # ### end Alembic commands ###
