"""empty message

Revision ID: 0da29d9e50a1
Revises: 78db059cf0ff
Create Date: 2018-10-14 19:47:07.016940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0da29d9e50a1'
down_revision = '78db059cf0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('glicko_ratings')
    op.drop_column('races', 'cached')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('cached', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('glicko_ratings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('races', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['races'], ['races.id'], name='glicko_ratings_races_fkey'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='glicko_ratings_school_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='glicko_ratings_pkey')
    )
    # ### end Alembic commands ###
