"""empty message

Revision ID: 293b7a8fd9a3
Revises: 04a56d5a9a42
Create Date: 2018-10-15 16:20:50.441589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293b7a8fd9a3'
down_revision = '04a56d5a9a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('year', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_seasons_year'), 'seasons', ['year'], unique=False)
    op.drop_index('ix_seasons_name', table_name='seasons')
    op.drop_column('seasons', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seasons_year'), table_name='seasons')
    op.drop_column('seasons', 'year')
    # ### end Alembic commands ###
