"""empty message

Revision ID: 78db059cf0ff
Revises: 5e58930937d7
Create Date: 2018-10-12 17:21:10.066996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78db059cf0ff'
down_revision = '5e58930937d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('cached', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'cached')
    # ### end Alembic commands ###
