"""empty message

Revision ID: b1affc30bf0d
Revises: 05104e75a3e3
Create Date: 2018-10-12 15:01:33.743889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1affc30bf0d'
down_revision = '05104e75a3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('opponent_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'races', 'schools', ['opponent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'races', type_='foreignkey')
    op.drop_column('races', 'opponent_id')
    # ### end Alembic commands ###
