"""empty message

Revision ID: b3da5ec2597a
Revises: d26642aefe62
Create Date: 2018-11-03 12:51:19.282008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3da5ec2597a'
down_revision = 'd26642aefe62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'created_date')
    # ### end Alembic commands ###
